db:
         image: postgres:latest
         restart: always
         ports:
         - "6432:5432"
         volumes:
         - ./sql_init:/docker-entrypoint-initdb.d
         - ./data/pgdata:/var/lib/postgresql/data
         environment:
         - POSTGRES_USER     = postgres
         - POSTGRES_PASSWORD = postgres
